from __future__ import annotations


def _r(id, title, assessment, description, solution, comments):
    return {
        "id": id,
        "title": title,
        "assessment": assessment,
        "description": description,
        "solution": solution,
        "comments": comments,
    }

CIS16_RULES = [
_r("1.1","Ensure packages are obtained from authorized repositories","Manual","Review PostgreSQL package origins and enabled software repositories.","Remove unapproved repositories and install PostgreSQL only from organization-approved distribution/vendor or official PGDG repositories.","Untrusted package sources can introduce modified or malicious database binaries."),
_r("1.2","Install only required packages","Manual","Inventory PostgreSQL-related packages and identify components that are not required for the server role.","Remove unnecessary PostgreSQL add-ons, administration web tools, documentation packages, and unused extensions according to the approved build standard.","Reducing installed software reduces attack surface."),
_r("1.3","Ensure systemd Service Files Are Enabled","Automated","Confirm the intended PostgreSQL systemd service is enabled on Linux hosts.","Enable the intended PostgreSQL service with systemctl enable <service> after validating the correct instance.","Disabled service registration can cause unexpected availability and recovery behavior."),
_r("1.4","Ensure Data Cluster Initialized Successfully","Automated","Verify the PostgreSQL data cluster exists, has a PG_VERSION file, and uses restrictive ownership/permissions.","Initialize the intended cluster as the PostgreSQL service account and correct PGDATA ownership and permissions.","Incorrect cluster initialization or ownership can expose database files or prevent safe startup."),
_r("1.5","Ensure the Latest Security Patches are Applied","Manual","Compare the running PostgreSQL 16 minor release with the current supported PostgreSQL 16 minor release.","Apply the current PostgreSQL 16 minor release after testing and review its release notes before production rollout.","Minor PostgreSQL releases include security, data-corruption, and reliability fixes."),
_r("1.6","Verify That 'PGPASSWORD' is Not Set in Users' Profiles","Automated","Search common shell profiles and environment files for persistent PGPASSWORD assignments.","Remove PGPASSWORD from profiles/scripts and use peer authentication, a protected password file, certificate authentication, or an approved secret mechanism.","PGPASSWORD stores a reusable database secret in clear text."),
_r("1.7","Verify That the 'PGPASSWORD' Environment Variable is Not in Use","Automated","Inspect process environments for active PGPASSWORD variables.","Stop using PGPASSWORD in long-lived processes and migrate to a protected authentication mechanism.","Process environment variables can expose database credentials."),

_r("2.1","Ensure the file permissions mask is correct","Manual","Check the postgres operating-system account umask and determine whether new files default to owner-only permissions.","Set the postgres account umask to 0077 or a more restrictive equivalent in the appropriate profile/service configuration.","A permissive umask can make newly created PostgreSQL files readable or writable by other accounts."),
_r("2.2","Ensure extension directory has appropriate ownership and permissions","Automated","Determine PostgreSQL's extension directory and verify root ownership with non-writable permissions for unprivileged users.","Set the extension directory owner to root:root and permissions to 0755, then validate extension file integrity.","Writable extension files can enable arbitrary code execution in the database process."),
_r("2.3","Disable PostgreSQL Command History","Automated","Search PostgreSQL client history files and determine whether history is disabled or redirected to /dev/null.","Remove existing .psql_history files and configure HISTFILE/PSQL_HISTORY to /dev/null or link history to /dev/null.","psql history can retain passwords, keys, sensitive SQL, or confidential data."),
_r("2.4","Ensure Passwords are Not Stored in the service file","Manual","Search per-user and global pg_service.conf files for password parameters.","Remove password entries from PostgreSQL connection service files and use a protected authentication mechanism.","Service files may be broadly readable and can expose credentials."),

_r("3.1.2","Ensure the log destinations are set correctly","Automated","Validate PostgreSQL log_destination is configured to an intended supported destination.","Set log_destination to the organization's approved destinations such as stderr/csvlog/jsonlog/syslog and reload configuration.","Missing or inappropriate log destinations can cause audit events to be lost."),
_r("3.1.3","Ensure the logging collector is enabled","Automated","Verify logging_collector is enabled where file-based stderr/csvlog/jsonlog collection is required.","Set logging_collector=on and restart PostgreSQL where required.","Without the collector, expected PostgreSQL log records can be lost."),
_r("3.1.4","Ensure the log file destination directory is set correctly","Automated","Verify log_directory is explicitly configured to a valid, non-root directory consistent with logging policy.","Configure log_directory to a protected log location, preferably outside PGDATA when operationally appropriate.","Incorrect log paths can lose logs, mix duties, or fill the data filesystem."),
_r("3.1.5","Ensure the filename pattern for log files is set correctly","Automated","Validate log_filename uses a usable rotation-friendly filename pattern.","Configure a time-varying log_filename such as postgresql-%Y%m%d.log in accordance with retention policy.","Predictable rotation prevents unbounded single log files and supports forensic retention."),
_r("3.1.6","Ensure the log file permissions are set correctly","Automated","Verify log_file_mode limits log access to the database owner or an explicitly authorized group.","Set log_file_mode to 0600, or 0640 only when group read access is explicitly required.","Database logs frequently contain sensitive statements, identifiers, and error detail."),
_r("3.1.7","Ensure 'log_truncate_on_rotation' is enabled","Automated","Check log_truncate_on_rotation and its interaction with log naming/rotation policy.","Set log_truncate_on_rotation=on when required by the benchmark and ensure the filename pattern does not cause unintended data loss.","Rotation settings must avoid both log loss and unbounded growth."),
_r("3.1.8","Ensure the maximum log file lifetime is set correctly","Automated","Check log_rotation_age and verify logs rotate at least daily unless policy requires more frequent rotation.","Set log_rotation_age to 1d or a shorter policy-approved interval and reload configuration.","Regular rotation limits file growth and improves log management."),
_r("3.1.9","Ensure the maximum log file size is set correctly","Automated","Check log_rotation_size and ensure size-based rotation is not disabled unless an approved alternate rotation mechanism exists.","Set a non-zero log_rotation_size appropriate for expected volume and storage capacity.","Very large log files increase loss and availability risks."),
_r("3.1.10","Ensure the correct syslog facility is selected","Manual","Review syslog_facility when PostgreSQL is configured to write to syslog.","Set syslog_facility to the organization-approved LOCAL0-LOCAL7 facility and align the syslog daemon routing policy.","Incorrect facility selection can misroute or drop database audit events."),
_r("3.1.11","Ensure syslog messages are not suppressed","Automated","Verify syslog_sequence_numbers is enabled when syslog logging is used.","Set syslog_sequence_numbers=on and reload PostgreSQL.","Sequence numbers help preserve evidence when syslog implementations collapse repeated messages."),
_r("3.1.12","Ensure syslog messages are not lost due to size","Automated","Verify syslog_split_messages is enabled for traditional syslog size limits unless an approved collector supports larger messages.","Set syslog_split_messages=on and reload PostgreSQL.","Oversized syslog records can be truncated or lost."),
_r("3.1.13","Ensure the program name for PostgreSQL syslog messages is correct","Automated","Verify syslog_ident clearly identifies PostgreSQL messages.","Set syslog_ident to a unique PostgreSQL service/cluster identifier and reload configuration.","A clear identifier improves routing and forensic attribution."),
_r("3.1.14","Ensure the correct messages are written to the server log","Automated","Check log_min_messages is at least as verbose as WARNING per the benchmark.","Set log_min_messages=warning or a more verbose approved level and reload configuration.","Logging too little can hide operational and security-relevant events."),
_r("3.1.15","Ensure the correct SQL statements generating errors are recorded","Automated","Check log_min_error_statement captures statements that generate ERROR or more severe conditions.","Set log_min_error_statement=error or a more verbose approved level and reload configuration.","Failed SQL is important evidence for troubleshooting and attack detection."),
_r("3.1.16","Ensure 'debug_print_parse' is disabled","Automated","Verify debug_print_parse is off.","Set debug_print_parse=off and reload configuration.","Debug parse output can expose sensitive query content and create excessive logging."),
_r("3.1.17","Ensure 'debug_print_rewritten' is disabled","Automated","Verify debug_print_rewritten is off.","Set debug_print_rewritten=off and reload configuration.","Query rewrite debug output can expose sensitive information."),
_r("3.1.18","Ensure 'debug_print_plan' is disabled","Automated","Verify debug_print_plan is off.","Set debug_print_plan=off and reload configuration.","Execution-plan debug output can leak data access patterns and flood logs."),
_r("3.1.19","Ensure 'debug_pretty_print' is enabled","Automated","Verify debug_pretty_print is enabled as required by the benchmark.","Set debug_pretty_print=on and reload configuration.","Readable debug structures assist analysis when debug logging is explicitly enabled."),
_r("3.1.20","Ensure 'log_connections' is enabled","Automated","Verify successful and attempted connections are logged.","Set log_connections=on and reload configuration; validate in a new session.","Connection logging supports authentication monitoring and incident reconstruction."),
_r("3.1.21","Ensure 'log_disconnections' is enabled","Automated","Verify session disconnections and durations are logged.","Set log_disconnections=on and reload configuration.","Without disconnect records, session timelines and duration analysis are incomplete."),
_r("3.1.22","Ensure 'log_error_verbosity' is set correctly","Automated","Verify log_error_verbosity is VERBOSE as required by this benchmark.","Set log_error_verbosity=verbose and reload configuration, subject to log data handling policy.","Verbose errors improve forensic detail but must be protected because they can contain sensitive context."),
_r("3.1.23","Ensure 'log_hostname' is set correctly","Automated","Verify log_hostname is disabled unless policy explicitly requires DNS hostname resolution.","Set log_hostname=off and reload configuration unless the organization has a documented need.","Disabling per-event DNS resolution avoids unnecessary overhead and resolver dependency."),
_r("3.1.24","Ensure 'log_line_prefix' is set correctly","Automated","Verify log_line_prefix contains timestamp, process/session, database, user, application, and client attribution fields.","Configure the benchmark-recommended log_line_prefix and reload PostgreSQL.","Rich attribution fields materially improve audit and incident response quality."),
_r("3.1.25","Ensure 'log_statement' is set correctly","Automated","Verify log_statement is not none; the benchmark recommends ddl unless policy requires another level.","Set log_statement=ddl or an approved stronger level, considering sensitive-data exposure and log volume.","DDL logging makes structural changes auditable."),
_r("3.1.26","Ensure 'log_timezone' is set correctly","Automated","Verify PostgreSQL log timestamps use UTC/GMT or the organization's approved common logging timezone.","Set log_timezone=UTC or GMT and reload configuration.","A common timezone prevents ambiguity when correlating distributed audit events."),
_r("3.2","Ensure the PostgreSQL Audit Extension (pgAudit) is enabled","Automated","Verify pgAudit is loaded and audit classes are configured.","Install the pgAudit build matching PostgreSQL 16, add pgaudit to shared_preload_libraries, configure pgaudit.log, and restart PostgreSQL.","pgAudit provides structured audit detail beyond ordinary statement logging."),

_r("4.1","Ensure Interactive Login is Disabled","Manual","Verify the postgres operating-system account password is locked and interactive login is restricted.","Lock the postgres OS account password and use named administrator accounts with controlled sudo escalation.","Direct shared postgres login weakens accountability and increases impact of credential compromise."),
_r("4.2","Ensure sudo is configured correctly","Manual","Review sudo rules that permit escalation to the postgres operating-system account.","Use a dedicated DBA group, require authentication, scope sudo to the postgres account, and protect sudoers files with restrictive permissions.","Controlled sudo provides attribution and limits access to the database service account."),
_r("4.3","Ensure excessive administrative privileges are revoked","Manual","Inventory PostgreSQL roles with SUPERUSER, CREATEROLE, CREATEDB, REPLICATION, or BYPASSRLS privileges.","Revoke unnecessary elevated role attributes and separate application owner, DDL, DML, and administrative duties.","Excess administrative privileges enable broad data and server compromise."),
_r("4.4","Lock Out Accounts if Not Currently in Use","Manual","Inventory login-enabled PostgreSQL roles and identify accounts that are no longer required.","Set unused accounts to NOLOGIN and remove/revoke obsolete credentials and memberships.","Dormant login accounts provide unnecessary attack paths."),
_r("4.5","Ensure excessive function privileges are revoked","Automated","Inspect SECURITY DEFINER functions and function EXECUTE grants for excessive privilege elevation.","Prefer SECURITY INVOKER; otherwise restrict EXECUTE to required roles and secure the function search_path.","Unsafe elevated functions can become privilege-escalation primitives."),
_r("4.6","Ensure excessive DML privileges are revoked","Manual","Review table-level INSERT, UPDATE, DELETE, TRUNCATE and related grants for application roles.","Revoke DML privileges not required by each role and use separate read/write roles according to least privilege.","Excessive DML privileges can enable unauthorized data modification or destruction."),
_r("4.7","Ensure Row Level Security (RLS) is configured correctly","Manual","Review tables that require row-level restrictions, their policies, and roles with BYPASSRLS.","Enable RLS where required, define explicit policies, and revoke BYPASSRLS from unauthorized roles.","Incorrect RLS design can expose or modify rows outside a user's authorization boundary."),
_r("4.8","Ensure the set_user extension is installed","Automated","Verify the set_user extension is available/configured for audited database superuser escalation as required by the benchmark.","Install the PostgreSQL 16 set_user extension, preload/configure it, grant controlled escalation functions, and remove direct superuser login where operationally feasible.","Audited role escalation provides better accountability than routine direct superuser login."),
_r("4.9","Make use of predefined roles","Manual","Review superuser accounts and determine whether PostgreSQL predefined roles can replace broad SUPERUSER access.","Grant narrowly scoped predefined roles such as pg_monitor where sufficient and revoke unnecessary SUPERUSER privileges.","Predefined roles support least-privilege administration."),

_r("5.1","Do Not Specify Passwords in the Command Line","Manual","Inspect process arguments and shell histories for PostgreSQL connection URIs or password parameters.","Use interactive password prompting, protected password files, certificates, peer authentication, or approved secret injection instead of command-line passwords.","Command-line credentials can be exposed in process listings and shell history."),
_r("5.2","Ensure PostgreSQL is Bound to an IP Address","Manual","Check listen_addresses and ensure PostgreSQL is not listening on every interface unless explicitly required.","Bind PostgreSQL only to specific required IPv4/IPv6 addresses and enforce network controls.","Restricting listener interfaces reduces network attack surface."),
_r("5.3","Ensure login via \"local\" UNIX Domain Socket is configured correctly","Manual","Review local pg_hba rules and prefer peer authentication for UNIX-domain socket access.","Configure restrictive local rules using peer authentication and reload PostgreSQL after validation.","Peer authentication binds database identity to the authenticated OS account."),
_r("5.4","Ensure login via \"host\" TCP/IP Socket is configured correctly","Manual","Review TCP/IP pg_hba rules for insecure authentication methods and unencrypted access.","Use hostssl with scram-sha-256 or an approved external/certificate method; reject unencrypted and trust/password/ident/md5 access where prohibited.","Weak host authentication can enable credential theft, replay, or unauthorized remote access."),
_r("5.5","Ensure per-account connection limits are used","Automated","Check login roles for unlimited rolconnlimit values.","Set a reasonable CONNECTION LIMIT on each login role based on application requirements.","Per-role limits reduce resource-exhaustion and denial-of-service risk."),
_r("5.6","Ensure Password Complexity is configured","Manual","Verify the benchmark's passwordcheck library is loaded where local password complexity checking is required.","Configure an approved password policy mechanism; if following the benchmark literally, preload passwordcheck and restart PostgreSQL.","Strong local authentication policy reduces brute-force and weak-password risk; external identity systems may provide stronger controls."),

_r("6.1","Understanding attack vectors and runtime parameters","Manual","Review PostgreSQL runtime parameters and configuration change sources for unexpected deviations.","Maintain an approved configuration baseline, audit ALTER SYSTEM/configuration changes, and investigate unauthorized parameter changes.","Runtime parameters can affect availability, auditing, integrity, and code-loading behavior."),
_r("6.2","Ensure 'backend' runtime parameters are configured correctly","Automated","Validate security-relevant backend/superuser-backend settings including index handling, debug support, and connection logging.","Restore backend parameters to approved baseline values and restart PostgreSQL when the parameter context requires it.","Backend parameter manipulation can degrade availability or obscure activity."),
_r("6.3","Ensure 'Postmaster' Runtime Parameters are Configured","Manual","Review postmaster-context settings and startup options against an approved baseline.","Correct unauthorized postmaster settings in configuration/startup options and perform a controlled restart.","Postmaster settings control cluster-wide memory, files, networking, recovery, and process behavior."),
_r("6.4","Ensure 'SIGHUP' Runtime Parameters are Configured","Manual","Review reloadable SIGHUP settings and configuration file sources against the approved baseline.","Restore unauthorized values in postgresql.conf/postgresql.auto.conf and reload PostgreSQL after validation.","Reloadable parameters can change security behavior without a restart."),
_r("6.5","Ensure 'Superuser' Runtime Parameters are Configured","Manual","Review superuser-only settings for dangerous or unexpected values.","Restore superuser settings to an approved baseline and investigate the source of unauthorized changes.","Compromised superuser settings can weaken logging, integrity checks, or code execution controls."),
_r("6.6","Ensure 'User' Runtime Parameters are Configured","Manual","Review user-context parameters and role/database settings for dangerous persistent overrides.","Remove unauthorized ALTER ROLE/ALTER DATABASE settings and enforce an approved baseline for application roles.","User-settable parameters can influence resource use, query behavior, logging, and object resolution."),
_r("6.7","Ensure FIPS 140-2 OpenSSL Cryptography Is Used","Automated","Check whether the host is operating in the benchmark-required FIPS cryptographic mode and whether OpenSSL reports FIPS capability.","Enable the organization-required FIPS mode on a validated platform and reboot/restart components as required.","Validated cryptographic modules may be mandatory for regulated environments."),
_r("6.8","Ensure TLS is enabled and configured correctly","Automated","Verify PostgreSQL TLS is enabled and certificate/key settings are configured.","Configure ssl=on with a trusted production certificate/private key, restrictive key permissions, and hostssl rules; restart as required.","TLS protects database traffic from disclosure and tampering in transit."),
_r("6.9","Ensure the TLSv1.0 and TLSv1.1 Protocols are Disabled","Automated","Verify ssl_min_protocol_version is TLSv1.2 or TLSv1.3.","Set ssl_min_protocol_version to TLSv1.2 or preferably TLSv1.3 and reload PostgreSQL.","TLS 1.0/1.1 are obsolete and lack modern cryptographic protections."),
_r("6.10","Ensure Weak SSL/TLS Ciphers Are Disabled","Automated","Verify ssl_ciphers contains only strong forward-secret cipher suites allowed by the benchmark.","Configure ssl_ciphers to a reviewed subset of strong ECDHE/DHE AEAD suites and test all clients.","Weak or non-forward-secret cipher suites can permit downgrade, disclosure, or compromise of historical sessions."),
_r("6.11","Ensure the pgcrypto extension is installed and configured correctly","Manual","Determine whether protected data-at-rest requirements are met and whether pgcrypto is available where application-layer cryptography is used.","Install/create pgcrypto when appropriate and combine it with storage-level encryption and key-management controls based on data-owner requirements.","Encryption must be designed across storage, memory, application, backups, and key lifecycle."),

_r("7.1","Ensure a replication-only user is created and used for streaming replication","Manual","Check whether streaming replication uses a dedicated non-superuser REPLICATION role.","Create and use a dedicated LOGIN REPLICATION role with only required privileges and restrictive pg_hba rules.","Replication does not require SUPERUSER and should follow least privilege."),
_r("7.2","Ensure logging of replication commands is configured","Manual","Check log_replication_commands and related logging for replication activity.","Enable log_replication_commands and ensure replication events are collected by the audit/logging platform.","Replication activity can carry sensitive data and should be auditable."),
_r("7.3","Ensure base backups are configured and functional","Manual","Collect evidence that current base backups exist and are produced regularly using encrypted transport.","Implement scheduled base backups with pg_basebackup or pgBackRest, protect backup transport/storage, and test restoration.","Backups are required for recovery; an untested backup is not sufficient evidence of recoverability."),
_r("7.4","Ensure WAL archiving is configured and functional","Automated","Verify archive_mode plus archive_command/archive_library and inspect pg_stat_archiver for successful WAL archival.","Enable archive_mode and a secure archive command/library, then monitor pg_stat_archiver and protect the archive destination.","Secure WAL archiving is essential for PITR and can otherwise leak sensitive transaction data."),
_r("7.5","Ensure streaming replication parameters are configured correctly","Manual","Review replication roles, primary_conninfo, pg_hba, and active replication TLS state.","Require encrypted authenticated replication with a dedicated role and validate standby/primary connection settings.","Replication transports DDL, DML, passwords, and other sensitive information."),

_r("8.1","Ensure PostgreSQL subdirectory locations are outside the data cluster","Manual","Review log/temp/tablespace locations, filesystem separation, permissions, and temp_file_limit.","Place security/operationally sensitive or high-growth directories on appropriate protected filesystems and set temp_file_limit when temp tablespaces are not separated.","Filesystem separation reduces accidental data exposure and denial-of-service from a full PGDATA volume."),
_r("8.2","Ensure the backup and restore tool, 'pgBackRest', is installed and configured","Automated","Detect pgBackRest and validate that its repository/stanza configuration can be queried.","Install/configure pgBackRest, store repositories separately with restricted access, set retention, and perform regular restore testing.","A reliable backup system needs protected storage, retention, monitoring, and proven restoration."),
_r("8.3","Ensure miscellaneous configuration settings are correct","Manual","Review dynamic library paths, preload libraries, external PID location, and UNIX socket directories/permissions.","Restrict socket/library directories, remove unauthorized preload libraries, and keep writable paths out of privileged dynamic loading/search locations.","Writable library/socket paths can enable privilege abuse, code loading, or unauthorized local access."),
]

# CIS PostgreSQL 18 Benchmark v1.0.0 (2026-03-27) keeps the v1.1.0 PG16 catalog
# structure and adds one recommendation: 4.10 (login roles without a password).
CIS18_RULES = list(CIS16_RULES)
CIS18_RULES.insert(next(i for i,r in enumerate(CIS18_RULES) if r['id']=='5.1'),
_r("4.10","Ensure all accounts that can log in have passwords","Manual","Unless certificate-based authentication is used, every database account that can log in should have a password set. An account without a stored password can never authenticate with a password, so interactive use of such an account implies certificate or external authentication.","Set a valid password for every login role that is not certificate-based. Prefer ALTER ROLE ... PASSWORD or \\password; note that ALTER ROLE can emit the new password to the server log, so use a protected session and SCRAM-SHA-256.","Passwordless login roles rely entirely on alternative authentication and can become unmanaged access paths."),
)

CIS_RULES_BY_MAJOR = {16: CIS16_RULES, 18: CIS18_RULES}

BENCHMARKS = {
    16: {'label': 'CIS PostgreSQL 16 Benchmark v1.1.0', 'date': '2025-06-30'},
    18: {'label': 'CIS PostgreSQL 18 Benchmark v1.0.0', 'date': '2026-03-27'},
}

ESA_RULES = [
_r("ESA-01","Backup Freshness & Restore Readiness","Enhanced","Measure backup freshness, pgBackRest/base-backup evidence, verification signals, and restore-test evidence.","Define RPO/RTO, automate encrypted backups, run verification, and perform periodic isolated restore tests.","Backup existence alone does not prove recoverability."),
_r("ESA-02","Data Checksums & Corruption Signals","Enhanced","Check data_checksums and cluster checksum failure counters.","Enable checksums using supported PostgreSQL procedures and investigate any checksum failure immediately.","Checksums improve detection of storage/page corruption."),
_r("ESA-03","Stored Password Hash Audit","Enhanced","Inspect login-role password hashes for obsolete MD5 storage versus SCRAM-SHA-256.","Set password_encryption=scram-sha-256 and rotate affected role passwords after confirming client compatibility.","MD5 password verifiers are legacy and materially weaker than SCRAM."),
_r("ESA-04","Password Expiration & Credential Lifecycle","Enhanced","Inspect login roles for expired passwords and indefinitely valid local credentials.","Apply an organization-approved credential lifecycle or external identity system and disable expired/unused accounts.","Long-lived unmanaged credentials increase persistence risk."),
_r("ESA-05","pg_hba Rule Parse Errors","Enhanced","Query pg_hba_file_rules for invalid or unparseable authentication rules.","Correct rule syntax/ordering and reload PostgreSQL; verify the effective rules after each change.","A malformed rule may leave an older or unintended authentication policy active."),
_r("ESA-06","Configuration Parse / Shadowed Settings","Enhanced","Query pg_file_settings for errors, unapplied settings, and conflicting configuration entries.","Remove invalid/conflicting entries and keep one authoritative configuration path under change control.","Shadowed or rejected settings create a false sense of hardening."),
_r("ESA-07","Search Path Hijacking Risk","Enhanced","Identify writable schemas in effective search paths that could allow object/function shadowing.","Remove CREATE from untrusted schemas, use trusted schemas only, and explicitly qualify security-sensitive objects.","Writable search_path schemas can turn name resolution into code execution or privilege escalation."),
_r("ESA-08","Unsafe SECURITY DEFINER Functions","Enhanced","Detect SECURITY DEFINER functions with unsafe search_path or PUBLIC execution.","Set a safe function search_path, place pg_temp last, revoke PUBLIC EXECUTE, and grant only required roles.","SECURITY DEFINER functions execute with the owner's privileges and require defensive coding."),
_r("ESA-09","Dangerous Predefined Role Membership","Enhanced","Review memberships in server-file/program and broad read/write predefined roles.","Revoke high-risk predefined roles from accounts that do not have a documented operational requirement.","Roles such as pg_execute_server_program and server-file roles can approach operating-system level impact."),
_r("ESA-10","Actual TLS Session Coverage","Enhanced","Inspect active client sessions and identify remote sessions that are not using TLS.","Require hostssl, reject hostnossl where appropriate, and update clients to use validated TLS.","ssl=on does not guarantee that every client session is encrypted."),
_r("ESA-11","Client Certificate Verification / Anti-Spoofing","Enhanced","Review discoverable connection strings/service settings for sslmode and server identity verification.","Use sslmode=verify-full (or an equivalent approved identity-verification mechanism) for sensitive remote clients.","Encryption without server identity verification can remain vulnerable to active interception."),
_r("ESA-12","Replication Slot WAL Retention / DoS Risk","Enhanced","Inspect inactive/lost replication slots, retained WAL volume, and max_slot_wal_keep_size.","Drop abandoned slots, alert on retained WAL, and set a bounded max_slot_wal_keep_size where compatible with recovery design.","Abandoned replication slots can retain unbounded WAL and exhaust storage."),
_r("ESA-13","Container Privilege & Identity Risk","Enhanced","Inspect whether the selected PostgreSQL container is privileged, runs as root, or has excessive Linux capabilities/security-profile exceptions.","Run as a non-root UID where supported, drop unnecessary capabilities, avoid privileged mode, and enable normal seccomp/AppArmor/SELinux controls.","Excess container privilege increases the blast radius of a database compromise."),
_r("ESA-14","Container Secret Exposure","Enhanced","Inspect container environment variable names for embedded passwords/tokens/secrets without recording their values.","Move secrets out of environment/image metadata into a dedicated secret mechanism and rotate exposed credentials.","Container inspect metadata is commonly available to administrators and orchestration components."),
_r("ESA-15","Sensitive Host Mount Exposure","Enhanced","Inspect container mounts for Docker sockets, host root, /etc, and other high-risk host paths.","Remove broad host mounts and never expose the container runtime socket to the database container.","Sensitive host mounts can convert a container compromise into host compromise."),
_r("ESA-16","Database Port Exposure","Enhanced","Inspect container/host port publication and flag PostgreSQL exposed on all interfaces.","Bind 5432 only to required management/application interfaces and enforce network firewall/security-group restrictions.","Publishing PostgreSQL on 0.0.0.0/:: expands network attack surface."),
_r("ESA-17","Logical Decoding Output Plugin Allowlist (PostgreSQL 16.15+)","Enhanced","Check output_plugin_libraries introduced in PostgreSQL 16.15 and compare it with logical replication slot plugins.","Keep output_plugin_libraries limited to pgoutput, test_decoding, and explicitly reviewed required plugins only.","PostgreSQL 16.15 added this allowlist after a security issue where replication users could select arbitrary loadable output-plugin libraries."),
_r("ESA-18","Extension & Untrusted Language Inventory","Enhanced","Inventory installed extensions and untrusted procedural languages for review against an approved allowlist.","Remove unused/unapproved extensions and untrusted languages; restrict CREATE EXTENSION and library installation paths.","Extensions and untrusted languages can execute powerful server-side code."),
]

CIS_BY_ID = {16: {r['id']: r for r in CIS16_RULES}, 18: {r['id']: r for r in CIS18_RULES}}
ESA_BY_ID = {r['id']: r for r in ESA_RULES}
